<?php

/**
 * @file
 * Example module for Adminify.
 */

/**
 * Implements hook_adminify_info().
 */
function adminify_example_adminify_info() {
  $path = drupal_get_path('module', 'adminify_example');

  return array(
    'administrator' => array(
      'file' => 'administrator.yml',
      'path' => $path,
    ),
    'content editor' => array(
      'file' => 'content_editor.yml',
      'path' => $path
    ),
    'author' => array(
      'file' => 'author.yml',
      'path' => $path
    ),
  );
}
